# src/plots.py
import matplotlib.pyplot as plt
from pathlib import Path

def grafsens(tl, tr, left, right, name_fig, nameim):
    fig, ax = plt.subplots(3, 2)
    fig.suptitle(name_fig)
    fig.set_size_inches(18.5, 10.5)
    plt.subplots_adjust(wspace=0.143, hspace=0.36, bottom=0.11, left=0.045)
    # dibuja series (ajusta indices a tu estructura de datos)
    ax[0, 0].plot(tl, left[0])
    ax[0, 0].set_title("left shoulder")
    ax[0, 1].plot(tr, right[0])
    ax[0, 1].set_title("Right shoulder")
    ax[1, 0].plot(tl, left[1])
    ax[1, 0].set_title("left Elbow")
    ax[1, 1].plot(tr, right[1])
    ax[1, 1].set_title("Right Elbow")
    ax[2, 0].plot(tl, left[2])
    ax[2, 0].set_title("left wrist")
    ax[2, 1].plot(tr, right[2])
    ax[2, 1].set_title("Right wrist")
    plt.show()
    fig.savefig(nameim, dpi=100)
    print('figura ' + nameim + ' ha sido guardada')

def grafangle(df2, name_fig, nameim):
    
    fig, ax = plt.subplots(3, 2)
    fig.suptitle(name_fig)
    fig.set_size_inches(18.5, 10.5)
    plt.subplots_adjust(wspace=0.143, hspace= 0.36,bottom=0.11, left=0.045)
    ax[0, 0].plot(df2[0], df2[1],'g')
    ax[0, 0].set_title("Hombro izquierdo")
    ax[0, 1].plot(df2[0], df2[2],'r')
    ax[0, 1].set_title("Hombro derecho")
    ax[1, 0].plot(df2[0], df2[3],'g')
    ax[1, 0].set_title("Codo izquierdo")
    ax[1,1].plot(df2[0], df2[4], 'r')
    ax[1,1].set_title("Codo derecho")
    ax[2,0].plot(df2[0], df2[5], 'g')
    ax[2,0].set_title("Muñeca izquierda")
    ax[2,1].plot(df2[0], df2[6], 'r')
    ax[2,1].set_title("Muñeca derecha")
    plt.setp(ax[-1, :], xlabel='Tiempo (segundos)')
    plt.setp(ax[:, 0], ylabel='Ángulos (grados)')
    plt.show()
    fig.savefig(nameim, dpi=100)
    print('figura'+nameim+'ha sido guardada')

def bx_plot_rms(df2, name_fig):
    fig, ax = plt.subplots(3, 2)
    fig.suptitle(name_fig)
    plt.subplots_adjust(wspace=0.143, hspace=0.36, bottom=0.11, left=0.045)
    ax[0, 0].boxplot(df2[1])
    ax[0, 0].set_title("left shoulder")
    ax[0, 1].boxplot(df2[2])
    ax[0, 1].set_title("Right shoulder")
    ax[1, 0].boxplot(df2[3])
    ax[1, 0].set_title("left Elbow")
    ax[1, 1].boxplot(df2[4])
    ax[1, 1].set_title("Right Elbow")
    ax[2, 0].boxplot(df2[5])
    ax[2, 0].set_title("left wrist")
    ax[2, 1].boxplot(df2[6])
    ax[2, 1].set_title("Right wrist")
    plt.show()
